import { NgModule } from '@angular/core';
import {
  IgxButtonModule,
  IgxIconModule,
  IgxLayoutModule,
  IgxNavigationDrawerModule,
  IgxRippleModule,
  IgxToggleModule,
  IgxNavbarModule,
  IgxTabsModule,
  IgxCardModule,
  IgxGridModule,
  IgxSwitchModule,
  IgxInputGroupModule,
  IgxProgressBarModule,
  IgxBadgeModule,
  IgxAvatarModule,
} from 'igniteui-angular';

@NgModule({
  imports: [
    IgxButtonModule,
    IgxIconModule,
    IgxLayoutModule,
    IgxNavigationDrawerModule,
    IgxRippleModule,
    IgxToggleModule,
    IgxNavbarModule,
    IgxTabsModule,
    IgxCardModule,
    IgxGridModule.forRoot(),
    IgxSwitchModule,
    IgxInputGroupModule,
    IgxProgressBarModule,
    IgxBadgeModule,
    IgxAvatarModule,
  ],
  exports: [
    IgxButtonModule,
    IgxIconModule,
    IgxLayoutModule,
    IgxNavigationDrawerModule,
    IgxRippleModule,
    IgxToggleModule,
    IgxNavbarModule,
    IgxTabsModule,
    IgxCardModule,
    IgxGridModule,
    IgxSwitchModule,
    IgxInputGroupModule,
    IgxProgressBarModule,
    IgxBadgeModule,
    IgxAvatarModule,
  ],
})
export class IgniteModule {}
